// Code generated by "stringer -type SignalValueType -trimprefix SignalValueType"; DO NOT EDIT.

package descriptor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SignalValueTypeNone-0]
	_ = x[SignalValueTypeInt-1]
	_ = x[SignalValueTypeFloat32-2]
	_ = x[SignalValueTypeFloat64-3]
}

const _SignalValueType_name = "NoneIntFloat32Float64"

var _SignalValueType_index = [...]uint8{0, 4, 7, 14, 21}

func (i SignalValueType) String() string {
	if i >= SignalValueType(len(_SignalValueType_index)-1) {
		return "SignalValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SignalValueType_name[_SignalValueType_index[i]:_SignalValueType_index[i+1]]
}
